---
### Storage - first step, install the software wherever we need it
- hosts: master
  become_user: root
  tasks:
    - { include_vars: "../../vars/main.yml" }
    - { include: "../../{{shared_storage_system}}/tasks/install.yml", when: single_node_lvm }

### Storage - second step, configure and start the master
- hosts: master
  become_user: root
  tasks:
    - { include_vars: "../../vars/main.yml" }
    - { include: "../../{{shared_storage_system}}/tasks/start.yml", when: single_node_lvm }

### Storage - third step, configure and start the data servers
- hosts: master
  become_user: root
  tasks:
    - { include_vars: "../../vars/main.yml" }
    - { include: "../../{{shared_storage_system}}/tasks/connect.yml", when: single_node_lvm }

### Storage - fourth step, mount directories where needed
- hosts: master
  become_user: root
  tasks:
    - { include_vars: "../../vars/main.yml" }
    - { include: "../../{{shared_storage_system}}/tasks/mount.yml", when: single_node_lvm }
